import './globals.css'
export const metadata = {
  title: 'Teachable',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir='rtl'>
      <body>{children}</body>
    </html>
  )
}
